/* Automatically generated by './build/bin/build-entry.js' */

import Icon from '../packages/icon/index.js';
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Container from '../packages/container/index.js';
import Header from '../packages/header/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import Footer from '../packages/footer/index.js';
import Col from '../packages/col/index.js';
import Row from '../packages/row/index.js';
import Popover from '../packages/popover/index.js';
import Collapse from '../packages/collapse/index.js';
import CollapseItem from '../packages/collapse-item/index.js';
import Loading from '../packages/loading/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Icon,
  Button,
  ButtonGroup,
  Scrollbar,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Col,
  Row,
  Popover,
  Collapse,
  CollapseItem,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return;
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.map(component => {
    Vue.component(component.name, component);
  });

  Vue.use(Loading.directive);

  const ELEMENT = {};
  ELEMENT.size = opts.size || '';

  // Vue.prototype.$loading = Loading.service;
  // Vue.prototype.$msgbox = MessageBox;
  // Vue.prototype.$alert = MessageBox.alert;
  // Vue.prototype.$confirm = MessageBox.confirm;
  // Vue.prototype.$prompt = MessageBox.prompt;
  // Vue.prototype.$notify = Notification;
  // Vue.prototype.$message = Message;

  Vue.prototype.$ELEMENT = ELEMENT;
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '2.0.1',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Icon,
  Button,
  ButtonGroup,
  Scrollbar,
  Container,
  Header,
  Aside,
  Main,
  Footer,
  Col,
  Row,
  Popover,
  Collapse,
  CollapseItem
};
